### ISSUE TITLE
[Feature]: Add visual block for research articles

### ISSUE THREAD

**Issue by thinkjrs** [thinkjrs/lottamob#20]
**Is your feature request related to a problem? Please describe.**
Right now we have some images w/text uploaded for _research_, as opposed to the blog or article section, which have typical static images.

**Describe the solution you'd like**
This doesn't need to be an image and should be a styled box w/text & background color overlaying it. 

- [x] Add text using `title` param
- [x] Add text using `author` param
- [x] Add styled box/bg image

**Comment by Lottamob** [comment]
For the research articles, it sounded like you had an idea about what to do instead of using power point slides of different colors with the titles. I am open to anything. I think something easily clickable containing just the title and year of publication is best. Be could have the name of publication underneath this or included in the image to click on, with no extra text underneath it.

**Comment by thinkjrs** [comment]
> For the research articles, it sounded like you had an idea about what to do instead of using power point slides of different colors with the titles. I am open to anything. I think something easily clickable containing just the title and year of publication is best. Be could have the name of publication underneath this or included in the image to click on, with no extra text underneath it.

Yep that's what this issue solves!

**Comment by thinkjrs** [comment]
I'm going to close this for now, however, I'd like to randomize the colors. @Lottamob Let's tackle this when we're together next and i'll take you through some color swatches (it'll be like going to the paint store, but infinite!)

**Comment by Lottamob** [comment]
Okay, thank you!
